name =  input('What is your name? ')
print('UGH, I HATE YOU ' + name.upper() +'.')
color =  input('What is your favorite color? ')
print('UGH, I HATE ' + color.upper() +', THERE ARE SO MANY BETTER COLORS YOU STUPID BITCH.')
subject = input('What is your favorite subject in school? ')
print('UGH, I HATE ' + subject.upper()+ '.')
print('I HATE EVERYTHING ABOUT YOU NIGGA!')
